package constant

var InfluencerUsernames = []string{
	"RektProof",
	"Tradermayne",
	"fejau_inc",
	"Gold_Cryptoz",
	"Galois_Capital",
	"Moudinho3",
	"LDNCryptoClub",
	"RunnerXBT",
	"damskotrades",
	"peach_1340",
	"RookieXBT",
	"trading__horse",
	"NB1763",
	"CoinGurruu",
	"MustStopMurad",
	"jtradestar",
	"TheCryptoDog",
	"KaitoAI",
	"ihzn7",
	"cubantobacco",
	"CryptoDonAlt",
	"DarkCryptoLord",
	"4adybug",
	"_happyk21",
	"milesdeutscher",
	"LomahCrypto",
	"alphawifhat",
	"Saint_Pump",
	"0xGeeGee",
	"Vida_BWE",
	"CryptoTony__",
}
